import { useMemo, useRef, useState } from 'react'
import { Upload, Download, FileText, ShieldCheck, Clock } from 'lucide-react'
import { PageHeader, Card, Table, Badge, StatCard, SearchInput, Select, statusTone } from '../components/ui.jsx'
import { useApp } from '../context/DataContext.jsx'
import { downloadFile } from '../lib/download.js'
import { BRAND } from '../lib/brand.js'

const CATEGORIES = ['Onboarding', 'KYC', 'Tax', 'Compensation', 'Benefits']

export default function Documents() {
  const { documents, addDocument, toast, notify } = useApp()
  const [q, setQ] = useState('')
  const [cat, setCat] = useState('All categories')
  const fileRef = useRef(null)

  const rows = useMemo(() => documents.filter((d) =>
    d.name.toLowerCase().includes(q.toLowerCase()) && (cat === 'All categories' || d.category === cat)
  ), [documents, q, cat])

  const onPick = (e) => {
    const files = Array.from(e.target.files || [])
    if (files.length === 0) return
    files.forEach((f) => addDocument({
      name: f.name,
      category: cat === 'All categories' ? 'Onboarding' : cat,
      size: f.size < 1024 * 1024 ? Math.max(1, Math.round(f.size / 1024)) + ' KB' : (f.size / 1048576).toFixed(1) + ' MB',
    }))
    notify({ title: 'Document uploaded', detail: files[0].name + (files.length > 1 ? ' and ' + (files.length - 1) + ' more' : '') + ' awaiting verification', to: '/documents', kind: 'info' })
    toast('Upload complete', files.length + ' file' + (files.length > 1 ? 's' : '') + ' sent to HR Ops for verification')
    e.target.value = ''
  }

  const grab = (doc) => {
    const body = [
      BRAND.company + ' HRMS - demo document', '', 'File: ' + doc.name,
      'Category: ' + doc.category, 'Uploaded: ' + doc.uploaded, 'Status: ' + doc.status, '',
      'This is placeholder content generated by the demo build.',
      'In the live portal this would be the original file from the document vault.',
    ].join('\n')
    downloadFile(doc.name.replace(/\.pdf$/i, '') + '.txt', body)
    toast('Download started', doc.name + ' (demo placeholder)', 'info')
  }

  return (
    <>
      <PageHeader
        title="Documents"
        subtitle="Your personal document vault"
        actions={<>
          <input ref={fileRef} type="file" multiple className="hidden" onChange={onPick} />
          <button className="btn-primary" onClick={() => fileRef.current?.click()}><Upload size={13} /> Upload document</button>
        </>}
      />

      <div className="grid gap-4 sm:grid-cols-3 mb-4 stagger">
        <StatCard label="Total documents" value={documents.length} icon={FileText} tone="cyan" />
        <StatCard label="Verified" value={documents.filter((d) => d.status === 'Verified').length} icon={ShieldCheck} tone="green" />
        <StatCard label="Awaiting verification" value={documents.filter((d) => d.status === 'Pending').length} icon={Clock} tone="amber" />
      </div>

      <Card bodyClass="p-0">
        <div className="flex flex-wrap items-center gap-2 p-3 border-b border-line">
          <div className="w-full sm:w-64"><SearchInput value={q} onChange={setQ} placeholder="Search documents..." /></div>
          <Select value={cat} onChange={setCat} options={['All categories', ...CATEGORIES]} />
        </div>
        <Table
          columns={[
            { key: 'name', header: 'Document', render: (r) => (
              <span className="flex items-center gap-2">
                <FileText size={14} className="text-[#DC2626] shrink-0" />
                <span className="text-[13px] text-navy">{r.name}</span>
              </span>
            )},
            { key: 'category', header: 'Category', render: (r) => <Badge tone="blue">{r.category}</Badge> },
            { key: 'size', header: 'Size', mono: true },
            { key: 'uploaded', header: 'Uploaded on', mono: true },
            { key: 'status', header: 'Status', render: (r) => <Badge tone={statusTone(r.status)}>{r.status}</Badge> },
            { key: 'action', header: '', align: 'right', render: (r) => (
              <button className="btn-ghost px-2 py-1" onClick={() => grab(r)}><Download size={12} /> Download</button>
            )},
          ]}
          rows={rows}
          empty="No documents match your search."
        />
      </Card>
    </>
  )
}
