import { useState } from 'react'
import { Download, Wallet, TrendingUp, Receipt, PiggyBank } from 'lucide-react'
import { PageHeader, Card, Table, Badge, StatCard, Tabs, statusTone } from '../components/ui.jsx'
import { payslips, salaryBreakup, INR } from '../data/mock.js'
import { useApp } from '../context/DataContext.jsx'
import { useAuth } from '../context/AuthContext.jsx'
import { downloadFile, downloadCSV } from '../lib/download.js'

export default function Payroll() {
  const { toast } = useApp()
  const { user } = useAuth()
  const [tab, setTab] = useState('Payslips')
  const totalEarn = salaryBreakup.earnings.reduce((s, r) => s + r.monthly, 0)
  const totalDed = salaryBreakup.deductions.reduce((s, r) => s + r.monthly, 0)

  const payslipText = (p) => {
    const line = (a, b) => a.padEnd(34) + String(b).padStart(14)
    return [
      'FLEXILOANS - PAYSLIP (demo)', '='.repeat(48), '',
      'Employee   : ' + user.name + ' (' + user.id + ')',
      'Designation: ' + user.designation,
      'Pay period : ' + p.month, 'Pay date   : ' + p.date, '',
      'EARNINGS', '-'.repeat(48),
      ...salaryBreakup.earnings.map((r) => line(r.head, INR(r.monthly))),
      line('Total earnings', INR(totalEarn)), '',
      'DEDUCTIONS', '-'.repeat(48),
      ...salaryBreakup.deductions.map((r) => line(r.head, INR(r.monthly))),
      line('Total deductions', INR(totalDed)), '',
      '='.repeat(48), line('NET PAY', INR(p.net)), '='.repeat(48), '',
      'Generated by the FlexiLoans HRMS demo build. Not a real payslip.',
    ].join('\n')
  }

  const getPayslip = (p) => {
    downloadFile('payslip-' + p.month.toLowerCase().replace(/\s+/g, '-') + '.txt', payslipText(p))
    toast('Payslip downloaded', p.month + ' - net ' + INR(p.net), 'info')
  }

  const getForm16 = () => {
    downloadFile('form-16-fy-2025-26.txt', [
      'FLEXILOANS - FORM 16 SUMMARY (demo)', '='.repeat(48), '',
      'Employee : ' + user.name + ' (' + user.id + ')', 'PAN      : ' + user.pan,
      'Assessment year: 2026-27', '',
      'Gross salary        : ' + INR(totalEarn * 12),
      'Total deductions    : ' + INR(totalDed * 12),
      'Net taxable income  : ' + INR((totalEarn - totalDed) * 12), '',
      'Placeholder content from the demo build.',
    ].join('\n'))
    toast('Form 16 downloaded', 'FY 2025-26 summary (demo placeholder)', 'info')
  }

  const exportPayslips = () => {
    downloadCSV('flexiloans-payslips.csv', [
      { header: 'Pay period', key: 'month' }, { header: 'Pay date', key: 'date' },
      { header: 'Gross', key: 'gross' }, { header: 'Deductions', key: 'deductions' },
      { header: 'Net pay', key: 'net' }, { header: 'Status', key: 'status' },
    ], payslips)
    toast('Export ready', payslips.length + ' payslip rows exported to CSV')
  }

  return (
    <>
      <PageHeader
        title="Payroll"
        subtitle="Compensation, payslips and tax declarations"
        actions={<>
          <button className="btn-secondary" onClick={exportPayslips}><Download size={13} /> Export</button>
          <button className="btn-secondary" onClick={getForm16}><Download size={13} /> Download Form 16</button>
        </>}
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4 mb-4 stagger">
        <StatCard label="Monthly gross" value={INR(totalEarn)} hint="Fixed cost to company" icon={Wallet} tone="cyan" />
        <StatCard label="Monthly net" value={INR(totalEarn - totalDed)} hint="Credited on the last working day" icon={TrendingUp} tone="green" />
        <StatCard label="Monthly deductions" value={INR(totalDed)} hint="PF, PT and TDS" icon={Receipt} tone="amber" />
        <StatCard label="Annual CTC" value={INR(totalEarn * 12)} hint="Revised April 2026" icon={PiggyBank} tone="blue" />
      </div>

      <Tabs tabs={['Payslips', 'Salary structure', 'Tax declaration']} active={tab} onChange={setTab} />

      {tab === 'Payslips' && (
        <Card bodyClass="p-0">
          <Table
            columns={[
              { key: 'month', header: 'Pay period' },
              { key: 'date', header: 'Pay date', mono: true },
              { key: 'gross', header: 'Gross', align: 'right', mono: true, render: (r) => INR(r.gross) },
              { key: 'deductions', header: 'Deductions', align: 'right', mono: true, render: (r) => INR(r.deductions) },
              { key: 'net', header: 'Net pay', align: 'right', mono: true, render: (r) => <span className="font-semibold text-navy">{INR(r.net)}</span> },
              { key: 'status', header: 'Status', render: (r) => <Badge tone={statusTone(r.status)}>{r.status}</Badge> },
              { key: 'action', header: '', align: 'right', render: (r) => (
                <button className="btn-ghost px-2 py-1" disabled={r.status !== 'Paid'} onClick={() => getPayslip(r)}><Download size={12} /> Payslip</button>
              )},
            ]}
            rows={payslips}
          />
        </Card>
      )}

      {tab === 'Salary structure' && (
        <div className="grid gap-4 lg:grid-cols-2">
          <Card title="Earnings" subtitle="Effective April 2026" bodyClass="p-0">
            <Table
              columns={[
                { key: 'head', header: 'Component' },
                { key: 'monthly', header: 'Monthly', align: 'right', mono: true, render: (r) => INR(r.monthly) },
                { key: 'annual', header: 'Annual', align: 'right', mono: true, render: (r) => INR(r.annual) },
              ]}
              rows={salaryBreakup.earnings}
            />
            <div className="flex justify-between px-3 py-3 bg-navy text-white text-[13px] font-medium">
              <span>Total earnings</span><span className="font-mono">{INR(totalEarn)} / month</span>
            </div>
          </Card>

          <Card title="Deductions" subtitle="Statutory and voluntary" bodyClass="p-0">
            <Table
              columns={[
                { key: 'head', header: 'Component' },
                { key: 'monthly', header: 'Monthly', align: 'right', mono: true, render: (r) => INR(r.monthly) },
                { key: 'annual', header: 'Annual', align: 'right', mono: true, render: (r) => INR(r.annual) },
              ]}
              rows={salaryBreakup.deductions}
            />
            <div className="flex justify-between px-3 py-3 bg-canvas text-navy text-[13px] font-medium border-t border-line">
              <span>Total deductions</span><span className="font-mono">{INR(totalDed)} / month</span>
            </div>
          </Card>
        </div>
      )}

      {tab === 'Tax declaration' && (
        <Card title="Investment declaration FY 2026-27" subtitle="Window closes 15 January 2027">
          <div className="grid gap-4 sm:grid-cols-2">
            {[
              ['Section 80C', 150000, 112000],
              ['Section 80D - Health insurance', 25000, 25000],
              ['HRA exemption', 240000, 216000],
              ['Section 80CCD(1B) - NPS', 50000, 0],
            ].map(([head, limit, declared]) => (
              <div key={head} className="rounded-lg border border-line p-3.5">
                <div className="flex justify-between items-baseline">
                  <p className="text-[13px] font-medium text-navy">{head}</p>
                  <Badge tone={declared >= limit ? 'green' : declared > 0 ? 'amber' : 'gray'}>
                    {declared >= limit ? 'Maxed' : declared > 0 ? 'Partial' : 'Not declared'}
                  </Badge>
                </div>
                <p className="text-[12px] text-muted mt-1.5 font-mono">{INR(declared)} declared of {INR(limit)}</p>
                <div className="h-1.5 w-full rounded-full bg-line overflow-hidden mt-2">
                  <div className="h-full rounded-full bg-cyan" style={{ width: Math.min(100, (declared / limit) * 100) + '%' }} />
                </div>
              </div>
            ))}
          </div>
          <div className="mt-4 rounded-lg border-l-[3px] border-cyan bg-cyan-bg px-3.5 py-3">
            <p className="text-[12px] text-[#374151]">
              You are on the <strong>new tax regime</strong>. Deductions under 80C and 80D do not reduce taxable income under this regime.
              Switch regimes from Settings before the declaration window closes if you want them applied.
            </p>
          </div>
        </Card>
      )}
    </>
  )
}
